Update index.bs
w3c-ccg/DID-Linked-Resources pull request #4
Opened 2024-09-24 05:03 UTC by Tweeddalex

2024-09-24 08:19 UTC, peacekeeper commented
I think it would be good to split this PR into two separate PRs.

+1 to changing UUIDs to more generic "unique identifier", depending on what a certain DID method may want to use.

Regarding ambiguity around verification relationships, that's a bit more tricky. First, I think the text doesn't say whether a verification relationship is required at all (and which one), or if it's enough to use any verification method in the DID document. And second, the logic described now in this PR would differ from e.g. how some implementations verify signatures on a VC, and from an algorithm described in the "Controller Documents" spec: https://w3c.github.io/controller-document/#retrieve-verification-method

So I'd propose to maybe make this PR only about the UUIDs, and create a separate PR about the control topic?

2024-09-24 08:41 UTC, ankurdotb requested changes
Agreed with Markus that we can perhaps split this into two PRs, in case there's more of a debate to be had about the control topic.

2024-09-24 08:41 UTC, ankurdotb commented on index.bs
> +"Resources" SHOULD be identifiable using a Decentralized Identifier (DID) and a permanently-accessible unique identifier to fetch the Resource from a Verifiable Data Registry or other storage endpoin
Should we start using RIDs ("Resource Identifiers") like DIDs?

2024-09-24 08:41 UTC, ankurdotb commented on index.bs
> +<div class="note"> <b>Note:</b> There is ambiguity in the DID Core specification around how Verification Method relationships can be used for different purposes. For example, some methods may use key
I would say this should be the key(s) mentioned under authentication, which is the normative section in DID Core specification for the DID subject to authenticate. This is a clearer way of stating this, rather than stating the keys in the "Verification Methods" are used. A key might be mentioned under Verification Methods, but NOT referenced under `authentication`. A good example of this is how Dock defines BBS+ related keys in Verification Methods, but does not reference them in the `authentication` section. Finally, you can have inline definitions of keys in `authentication`.

2024-09-24 08:51 UTC, peacekeeper commented on index.bs
> +<div class="note"> <b>Note:</b> There is ambiguity in the DID Core specification around how Verification Method relationships can be used for different purposes. For example, some methods may use key
I agree.. My comment was also essentially that both embedded and referenced keys should be supported, to be more aligned with VCs, Controller Documents, and other things.

2024-09-24 15:37 UTC, TallTed commented on index.bs
> +"Resources" SHOULD be identifiable using a Decentralized Identifier (DID) and a permanently-accessible unique identifier to fetch the Resource from a Verifiable Data Registry or other storage endpoin
> Should we start using RIDs ("Resource Identifiers") like DIDs?

Premature abbreviation, I think. [TLAs](https://www.abbreviations.com/TLA) are in short supply, and [RID](https://www.abbreviations.com/RID) is already overloaded

2024-09-24 15:43 UTC, TallTed commented on index.bs
> +Using unique identifiers ensures a high level of confidence that no two identical Resource IDs will ever be created. This is important for ensuring the integrity and unambiguity of each individual DI
```suggestion
Using unique identifiers increases confidence that no two identical Resource IDs will ever be created. This is important for ensuring the integrity and unambiguity of each individual DID-Linked Resource. Throughout this specification, we will therefore use UUIDs for example Resource IDs, although different method implementations may specify other Resource ID formats.
```

2024-09-24 15:47 UTC, TallTed commented on index.bs
> +<div class="note"> <b>Note:</b> There is ambiguity in the DID Core specification around how Verification Method relationships can be used for different purposes. For example, some methods may use key
```suggestion
<div class="note"> <b>Note:</b> The DID Core specification is ambiguous about how Verification Method relationships can be used for different purposes. For example, some methods use keys embedded within fields like 'capabilityDelegation' or 'keyAgreement' for specific purposes. To avoid ambiguity in implementation, this specification requires that the keys used to create DID-Linked Resources are described in the Verification Method section of the parent DID Document.
```

2024-09-25 05:42 UTC, Tweeddalex commented on index.bs
> +"Resources" SHOULD be identifiable using a Decentralized Identifier (DID) and a permanently-accessible unique identifier to fetch the Resource from a Verifiable Data Registry or other storage endpoin
@peacekeeper @ankurdotb have removed the "control" section and will keep this just to the changes in identifier

2024-09-25 05:43 UTC, Tweeddalex commented on index.bs
> +<div class="note"> <b>Note:</b> There is ambiguity in the DID Core specification around how Verification Method relationships can be used for different purposes. For example, some methods may use key
I like this approach as well

2024-09-25 05:46 UTC, Tweeddalex commented on index.bs
> +<div class="note"> <b>Note:</b> There is ambiguity in the DID Core specification around how Verification Method relationships can be used for different purposes. For example, some methods may use key
@TallTed removing this section for now, and will spin this into a new PR

2024-09-25 05:49 UTC, Tweeddalex commented on index.bs
> +Using unique identifiers ensures a high level of confidence that no two identical Resource IDs will ever be created. This is important for ensuring the integrity and unambiguity of each individual DI
Change made in latest commit

2024-09-25 20:06 UTC, peacekeeper approved these changes

2024-09-26 07:28 UTC, merged